#ifndef PROJECT_EULER_SOLUTIONS_ALL_SOLUTIONS_H
#define PROJECT_EULER_SOLUTIONS_ALL_SOLUTIONS_H

// Include all solution headers

#include "Problem_1.h"

#endif //PROJECT_EULER_SOLUTIONS_ALL_SOLUTIONS_H
